import type {
  Asset,
  ConstraintPolicy,
  CoordinationCheckpoint,
  DataQualitySignal,
  FlexibilityEnvelope,
  IntegrationStandard,
  IntegrationSource,
  MarketEnrollment,
  MarketSignal,
  ObjectiveWeights,
  OperatorRecommendation,
  TelemetrySample,
} from './types'

export const assets: Asset[] = [
  {
    id: 'bess-sutter',
    name: 'Sutter BESS Cluster',
    type: 'Battery',
    region: 'CAISO NP15',
    capacityMw: 142,
    availableMw: 119,
    stateOfCharge: 61,
    readiness: 94,
    degradationCost: 18,
    customerFlex: 97,
    telemetry: 'healthy',
    constraint: 'Reserve 28 MWh for evening RA obligation',
  },
  {
    id: 'ev-bay',
    name: 'Bay Logistics EV Depots',
    type: 'EV charger',
    region: 'CAISO NP15',
    capacityMw: 38,
    availableMw: 21,
    stateOfCharge: 72,
    readiness: 78,
    degradationCost: 9,
    customerFlex: 63,
    telemetry: 'limited',
    constraint: 'Departure windows start at 16:30',
  },
  {
    id: 'solar-rio',
    name: 'Rio Vista Solar',
    type: 'Solar',
    region: 'CAISO SP15',
    capacityMw: 84,
    availableMw: 71,
    readiness: 89,
    degradationCost: 2,
    customerFlex: 99,
    telemetry: 'healthy',
    constraint: 'Curtailment limited by PPA floor',
  },
  {
    id: 'hvac-east',
    name: 'East Bay Flex Loads',
    type: 'Building load',
    region: 'CAISO NP15',
    capacityMw: 53,
    availableMw: 34,
    readiness: 82,
    degradationCost: 4,
    customerFlex: 72,
    telemetry: 'delayed',
    constraint: 'Comfort band must stay within 2.2 F',
  },
  {
    id: 'gen-north',
    name: 'North Valley Backup Gen',
    type: 'Generator',
    region: 'CAISO NP15',
    capacityMw: 47,
    availableMw: 39,
    readiness: 76,
    degradationCost: 24,
    customerFlex: 88,
    telemetry: 'healthy',
    constraint: 'NOx runtime cap: 7.5 hours remaining',
  },
]

export const marketSignals: MarketSignal[] = [
  {
    product: 'Energy arbitrage',
    region: 'CAISO NP15',
    price: 184,
    confidence: 82,
    obligationMw: 74,
    interval: '14:00-16:00',
    weatherSignal: 'Warm evening ramp',
    gridCondition: 'scarcity',
    risk: 'medium',
  },
  {
    product: 'Frequency regulation',
    region: 'CAISO NP15',
    price: 41,
    confidence: 91,
    obligationMw: 48,
    interval: '13:30-15:30',
    weatherSignal: 'Stable',
    gridCondition: 'normal',
    risk: 'low',
  },
  {
    product: 'Demand response',
    region: 'CAISO NP15',
    price: 126,
    confidence: 73,
    obligationMw: 61,
    interval: '17:00-20:00',
    weatherSignal: 'Warm evening ramp',
    gridCondition: 'scarcity',
    risk: 'medium',
  },
  {
    product: 'Capacity event',
    region: 'CAISO SP15',
    price: 212,
    confidence: 68,
    obligationMw: 56,
    interval: '18:00-21:00',
    weatherSignal: 'High solar drop',
    gridCondition: 'congested',
    risk: 'high',
  },
  {
    product: 'Reserve',
    region: 'CAISO NP15',
    price: 58,
    confidence: 87,
    obligationMw: 36,
    interval: '15:00-19:00',
    weatherSignal: 'Stable',
    gridCondition: 'normal',
    risk: 'low',
  },
]

export const marketEnrollments: MarketEnrollment[] = [
  {
    id: 'enroll-bess-energy-np15',
    assetId: 'bess-sutter',
    program: 'CAISO NGR energy bidding',
    product: 'Energy arbitrage',
    region: 'CAISO NP15',
    status: 'active',
    minOfferMw: 10,
    maxOfferMw: 110,
    telemetryRequirementSeconds: 10,
    settlementRisk: 'low',
    expiresAt: '2026-12-31',
  },
  {
    id: 'enroll-bess-reg-np15',
    assetId: 'bess-sutter',
    program: 'CAISO regulation up/down',
    product: 'Frequency regulation',
    region: 'CAISO NP15',
    status: 'active',
    minOfferMw: 5,
    maxOfferMw: 54,
    telemetryRequirementSeconds: 4,
    settlementRisk: 'medium',
    expiresAt: '2026-09-30',
  },
  {
    id: 'enroll-ev-dr-np15',
    assetId: 'ev-bay',
    program: 'Utility managed charging DR',
    product: 'Demand response',
    region: 'CAISO NP15',
    status: 'active',
    minOfferMw: 4,
    maxOfferMw: 24,
    telemetryRequirementSeconds: 60,
    settlementRisk: 'medium',
    expiresAt: '2026-10-15',
  },
  {
    id: 'enroll-hvac-dr-np15',
    assetId: 'hvac-east',
    program: 'Commercial load shed DR',
    product: 'Demand response',
    region: 'CAISO NP15',
    status: 'active',
    minOfferMw: 8,
    maxOfferMw: 31,
    telemetryRequirementSeconds: 90,
    settlementRisk: 'medium',
    expiresAt: '2026-08-01',
  },
  {
    id: 'enroll-gen-reserve-np15',
    assetId: 'gen-north',
    program: 'Non-spinning reserve',
    product: 'Reserve',
    region: 'CAISO NP15',
    status: 'pending',
    minOfferMw: 8,
    maxOfferMw: 38,
    telemetryRequirementSeconds: 30,
    settlementRisk: 'high',
    expiresAt: '2026-07-20',
  },
  {
    id: 'enroll-solar-capacity-sp15',
    assetId: 'solar-rio',
    program: 'SP15 capacity event pilot',
    product: 'Capacity event',
    region: 'CAISO SP15',
    status: 'active',
    minOfferMw: 12,
    maxOfferMw: 43,
    telemetryRequirementSeconds: 30,
    settlementRisk: 'high',
    expiresAt: '2026-11-01',
  },
]

export const objectiveWeights: ObjectiveWeights = {
  revenue: 0.32,
  reliability: 0.2,
  obligation: 0.18,
  degradation: 0.12,
  customer: 0.1,
  risk: 0.08,
}

export const integrationSources: IntegrationSource[] = [
  {
    system: 'vela.m1_ingestion',
    category: 'ISO / RTO data pipeline',
    signals: 'LMP, AS prices, outages, awards — CAISO, ERCOT, PJM, MISO, NYISO, ISO-NE, SPP, WECC',
    cadence: '5-15 min',
    adapter: 'vela/m1_ingestion/iso_connectors/',
    health: 'healthy',
  },
  {
    system: 'vela.m2_protocols',
    category: 'DER device telemetry',
    signals: 'MW, MWh, SOC, alarms, setpoints via DNP3, IEC 61850, Modbus TCP, OCPP, OpenADR, MQTT',
    cadence: '1-5 sec',
    adapter: 'vela/m2_protocols/',
    health: 'healthy',
  },
  {
    system: 'vela.m5_forecasting',
    category: 'Price and load forecasts',
    signals: 'LMP forecast, load profile, solar generation, ancillary service prices, spike risk',
    cadence: '15 min',
    adapter: 'vela/m5_forecasting/price_forecast.py · ensemble_forecast.py',
    health: 'healthy',
  },
  {
    system: 'vela.m6_optimizer',
    category: 'Dispatch optimization',
    signals: 'Optimal bid block, asset allocation, ramp schedule, CVaR exposure',
    cadence: 'Per interval',
    adapter: 'vela/m6_optimizer/milp.py · stochastic.py · co_optimization.py',
    health: 'healthy',
  },
  {
    system: 'vela.m8_market + m9_settlement',
    category: 'Market bidding and settlement',
    signals: 'Offer curves, AS co-optimization, DA/RT imbalance, daily revenue statement',
    cadence: 'Per interval / daily',
    adapter: 'vela/m8_market/offer_builder.py · vela/m9_settlement/settlement_engine.py',
    health: 'limited',
  },
  {
    system: 'vela.m7_explainability',
    category: 'Decision rationale',
    signals: 'SHAP attribution, plain-English dispatch narrative, dual variable analysis',
    cadence: 'Per recommendation',
    adapter: 'vela/m7_explainability/shap_explainer.py · dispatch_narrative.py',
    health: 'healthy',
  },
  {
    system: 'vela.m10_thermal + m12_demand_response',
    category: 'Building and DR control',
    signals: 'HVAC setpoints, comfort bands, elasticity scores, curtailment capacity',
    cadence: '5-15 min',
    adapter: 'vela/m10_thermal/ · vela/m12_demand_response/',
    health: 'delayed',
  },
  {
    system: 'vela.api (FastAPI)',
    category: 'Internal REST layer',
    signals: 'All domain data served via /assets, /dispatch, /market, /settlement, /telemetry, /forecasts',
    cadence: 'Real-time',
    adapter: 'vela/api/routers/ — 15 endpoint groups',
    health: 'healthy',
  },
]

export const integrationStandards: IntegrationStandard[] = [
  {
    id: 'ferc-2222-coordination',
    name: 'FERC Order 2222',
    domain: 'Market access',
    source: 'FERC',
    requirement: 'DER aggregations need market rules for locational eligibility, bidding parameters, metering, telemetry, and coordination.',
    velaRecord: 'MarketEnrollment',
    implementation: 'partial',
    note: 'Enrollment and coordination gates are modeled; regional tariff specifics still need adapter-level rules.',
  },
  {
    id: 'openadr-3',
    name: 'OpenADR 3.0',
    domain: 'DER control',
    source: 'OpenADR Alliance',
    requirement: 'Automated DR and DER messaging should carry event signals, targets, opt status, and customer/resource responses.',
    velaRecord: 'DispatchPlan',
    implementation: 'partial',
    note: 'Dispatch instructions are canonical, but event payload export and opt-status round trips are still mocked.',
  },
  {
    id: 'ieee-2030-5',
    name: 'IEEE 2030.5',
    domain: 'DER control',
    source: 'IEEE / utility programs',
    requirement: 'DER devices and aggregators need interoperable device capability, telemetry, control, and pricing/program signals.',
    velaRecord: 'FlexibilityEnvelope',
    implementation: 'partial',
    note: 'Flex envelopes capture capability and latency; device-program profile mapping is not implemented yet.',
  },
  {
    id: 'ieee-1547',
    name: 'IEEE 1547',
    domain: 'Interconnection',
    source: 'IEEE / NREL',
    requirement: 'Interconnected DERs need settings and operating constraints that preserve grid safety and reliability.',
    velaRecord: 'ConstraintPolicy',
    implementation: 'modeled',
    note: 'The policy model can hold interconnection and runtime limits; direct inverter settings are future adapter work.',
  },
  {
    id: 'adms-derms-coordination',
    name: 'ADMS / DERMS coordination',
    domain: 'Distribution operations',
    source: 'NREL',
    requirement: 'Distribution operations need DER visibility, local constraints, and feedback-aware control before bulk-market service delivery.',
    velaRecord: 'TelemetrySample',
    implementation: 'partial',
    note: 'Telemetry quality and coordination review are visible; feeder model and topology adapters are missing.',
  },
]

export const recommendations: OperatorRecommendation[] = [
  {
    action: 'sell',
    targetMw: 74,
    score: 86,
    window: '14:00-16:00',
    headline: 'Sell into NP15 scarcity while reserving battery headroom.',
    why:
      'The price signal is strong, asset readiness is high, and the battery fleet can cover the interval without breaching the evening capacity reserve.',
  },
  {
    action: 'reserve',
    targetMw: 36,
    score: 78,
    window: '15:00-19:00',
    headline: 'Keep fast-response capacity available for regulation and reserve.',
    why:
      'Lower revenue than energy arbitrage, but lower operational risk and strong telemetry confidence across batteries and generators.',
  },
  {
    action: 'shift',
    targetMw: 29,
    score: 72,
    window: '17:00-20:00',
    headline: 'Pre-cool and shift building load before the evening event.',
    why:
      'Load flexibility is useful, but customer comfort and telemetry lag make it a secondary recommendation.',
  },
  {
    action: 'store',
    targetMw: 42,
    score: 64,
    window: '11:00-13:00',
    headline: 'Charge batteries only if prices soften before the ramp.',
    why:
      'Storage has value if midday prices fall, but the current scarcity signal makes immediate charging less attractive than selling later.',
  },
  {
    action: 'curtail',
    targetMw: 12,
    score: 58,
    window: '12:30-14:00',
    headline: 'Curtail solar only as a congestion fallback.',
    why:
      'Curtailment protects interconnection limits, but PPA constraints and lost production make it the least preferred action.',
  },
]

export const dataQualitySignals: DataQualitySignal[] = [
  {
    label: 'Asset telemetry',
    source: 'EMS / SCADA + BMS',
    freshness: '1.2 sec',
    confidence: 96,
    impact: 'Primary dispatch limits are current',
    status: 'healthy',
  },
  {
    label: 'Customer rules',
    source: 'CRM / program rules',
    freshness: '18 min',
    confidence: 74,
    impact: 'EV and building load decisions need approval',
    status: 'watch',
  },
  {
    label: 'Weather ramp',
    source: 'Forecast API ensemble',
    freshness: '14 min',
    confidence: 82,
    impact: 'Supports evening scarcity forecast',
    status: 'healthy',
  },
  {
    label: 'Market awards',
    source: 'ISO/RTO feed',
    freshness: '5 min',
    confidence: 88,
    impact: 'Capacity and reserve obligations synced',
    status: 'healthy',
  },
]

export const telemetrySamples: TelemetrySample[] = [
  {
    assetId: 'bess-sutter',
    source: 'BMS / EMS',
    timestamp: '2026-06-05T18:54:48Z',
    realPowerMw: 6.2,
    reactivePowerMvar: 1.1,
    stateOfCharge: 61,
    breakerClosed: true,
    quality: 'valid',
  },
  {
    assetId: 'ev-bay',
    source: 'EVSE network',
    timestamp: '2026-06-05T18:49:22Z',
    realPowerMw: -8.7,
    stateOfCharge: 72,
    quality: 'estimated',
  },
  {
    assetId: 'hvac-east',
    source: 'BMS gateway',
    timestamp: '2026-06-05T18:38:09Z',
    realPowerMw: -18.4,
    quality: 'stale',
  },
]

export const flexibilityEnvelopes: FlexibilityEnvelope[] = [
  {
    assetId: 'bess-sutter',
    interval: '14:00-16:00',
    maxExportMw: 119,
    maxImportMw: 84,
    sustainedDurationMinutes: 102,
    rampRateMwPerMinute: 18,
    controlLatencySeconds: 4,
    telemetryLatencySeconds: 1.2,
    confidence: 94,
  },
  {
    assetId: 'ev-bay',
    interval: '14:00-16:00',
    maxExportMw: 0,
    maxImportMw: 21,
    sustainedDurationMinutes: 46,
    rampRateMwPerMinute: 4,
    controlLatencySeconds: 38,
    telemetryLatencySeconds: 26,
    confidence: 71,
  },
  {
    assetId: 'hvac-east',
    interval: '17:00-20:00',
    maxExportMw: 34,
    maxImportMw: 0,
    sustainedDurationMinutes: 88,
    rampRateMwPerMinute: 3,
    controlLatencySeconds: 95,
    telemetryLatencySeconds: 47,
    confidence: 68,
  },
]

export const constraintPolicies: ConstraintPolicy[] = [
  {
    id: 'ra-evening-reserve',
    assetId: 'bess-sutter',
    source: 'Capacity contract',
    rule: 'Reserve 28 MWh for evening resource adequacy obligation.',
    severity: 'binding',
    operatorApprovalRequired: true,
  },
  {
    id: 'ev-departure-window',
    assetId: 'ev-bay',
    source: 'Customer rules',
    rule: 'Do not compromise committed vehicle departure energy after 16:30.',
    severity: 'binding',
    operatorApprovalRequired: true,
  },
  {
    id: 'comfort-band',
    assetId: 'hvac-east',
    source: 'Building management system',
    rule: 'Maintain occupied-zone comfort within 2.2 F before rebound recovery.',
    severity: 'advisory',
    operatorApprovalRequired: false,
  },
]

export const coordinationCheckpoints: CoordinationCheckpoint[] = [
  {
    id: 'coord-aggregation-registration',
    label: 'Aggregation registration package',
    owner: 'Aggregator',
    requirement: 'Resource list, asset metadata, capacity range, and customer eligibility are consistent before market submission.',
    evidence: '5 assets linked to enrollment records; pending reserve enrollment remains outside the primary bid.',
    status: 'ready',
    risk: 'low',
    dueBy: 'T-120 min',
  },
  {
    id: 'coord-locational-eligibility',
    label: 'Locational eligibility',
    owner: 'RTO/ISO',
    requirement: 'Aggregation members must stay inside market-approved zones and product-specific aggregation boundaries.',
    evidence: 'NP15 energy and reserve bids use NP15 resources; SP15 solar remains isolated to capacity event logic.',
    status: 'ready',
    risk: 'low',
    dueBy: 'T-90 min',
  },
  {
    id: 'coord-distribution-review',
    label: 'Distribution review',
    owner: 'Distribution utility',
    requirement: 'Utility gets planned dispatch notice with feeder, interconnection, and local reliability context.',
    evidence: 'No feeder model adapter yet; operator should treat distribution review as manual before dispatch.',
    status: 'review',
    risk: 'medium',
    dueBy: 'T-60 min',
  },
  {
    id: 'coord-meter-telemetry',
    label: 'Metering and telemetry',
    owner: 'Internal',
    requirement: 'Dispatch-quality telemetry must meet product cadence, freshness, and settlement replay requirements.',
    evidence: 'BESS telemetry is valid; EVSE and building load sources are estimated or stale.',
    status: 'review',
    risk: 'medium',
    dueBy: 'T-30 min',
  },
  {
    id: 'coord-customer-rules',
    label: 'Customer constraint attestation',
    owner: 'Customer',
    requirement: 'Customer opt-outs, comfort bands, EV departure energy, and participation limits must be honored.',
    evidence: 'EV departure and RA reserve policies require operator approval before automatic release.',
    status: 'blocked',
    risk: 'high',
    dueBy: 'Before approval',
  },
  {
    id: 'coord-settlement-replay',
    label: 'Settlement replay evidence',
    owner: 'Internal',
    requirement: 'Every bid, dispatch instruction, override, and telemetry input needs replayable evidence for settlement review.',
    evidence: 'Model-run snapshot captures adapter refs, ranked decisions, dispatch plan, overrides, and settlement projection.',
    status: 'ready',
    risk: 'low',
    dueBy: 'Post-event',
  },
]
