apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: vela
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: vela-vpp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 100Gi
