apiVersion: v2
name: vela
description: VPP Dispatch Optimization Engine
type: application
version: 0.0.23
appVersion: "0.0.23"
keywords:
  - vpp
  - energy-storage
  - dispatch-optimization
maintainers:
  - name: Vela Team
