apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: vela-prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.50.1
      cacheLevel: Low
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
