apiVersion: v1
kind: Service
metadata:
  name: vela-api
  namespace: vela
  labels:
    app.kubernetes.io/name: vela-api
    app.kubernetes.io/part-of: vela-vpp
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  selector:
    app: vela-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
